version: '3'

services:
  postgres:
    image: postgres:11.22-bullseye
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  go-app:
    build:
      context: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8000:8000"